### ISSUE TITLE
Issues in identification of genes/isoforms based on the reference GTF in Talon:

### ISSUE THREAD

**Issue by aramaiah** [mortazavilab/TALON#55]
I used the Talon in Bioconda. I ran the Talon using blank GTF as reference for de novo genes identification. It was successful. However, when I used the output of Talon run-1 as input GTF reference, for identifying the genes using subreads data, it was keeping giving me the errors during 'talon_abundance' and 'talon_create_GTF' steps. I have used variety of names for -a and -g, but could not able to succeed. Could you help me to solve this issue?

**Comment by dewyman** [comment]
Hi,
When you initialize a TALON database with a blank GTF, you essentially get an empty database, which leads to problems downstream as you noticed because no genome build or annotation names got added. What I would recommend to get around this is to initialize with a dummy GTF like the one I've uploaded [here](https://github.com/mortazavilab/TALON/blob/master/src/talon/blank.gtf)- even having one mock GTF entry in the file means that the annotation name and build will be added to the database, where the downstream scripts should be able to find them. It is possible you will hit some other unusual behaviors since we didn't develop TALON for de novo annotation from the outset, but I'm happy to answer more questions as they come up. 
Best,
Dana

**Comment by aramaiah** [comment]
Hi,
Thank you for your response. I have used an actual GTF (output of first
Talon run) as input and I am doing a new run with isoseq data for novel
transcript discovery. I had used the test gtf that you had shared for the
previous run. I am happy to share the data if you wants to look at them.

Best,
Arun

**Comment by dewyman** [comment]
Hi Arun,
I'd be happy to take a look. You can send the GTF to me at dwyman@uci.edu.
Best,
Dana
