### ISSUE TITLE
Talon GTF - adding CDS

### ISSUE THREAD

**Issue by rsalz** [mortazavilab/TALON#71]
Hi,

I was wondering if there was a simple way to add features to the talon GTF such as CDS. Any recommendations?

TIA
Renee

**Comment by fairliereese** [comment]
For known transcripts, you could do this with a reference annotation that already has the CDS annotated (outside of TALON) and somehow merge it with the TALON GTF output. However since TALON is specifically designed with novel transcripts in mind, it would be difficult to get the CDSs of these specific transcripts which don't have annotated CDSs. 

I would advise trying to look for CDSs as a post-TALON analysis. For novel transcripts you could use something like [TransDecoder](https://github.com/TransDecoder/TransDecoder) which predicts ORFs and the most likely CDS from each transcript model. This has worked for our post-TALON analysis in the past. However, adding such functionality to TALON itself I believe is beyond the scope of the software.
