### ISSUE TITLE
memory requirement

### ISSUE THREAD

**Issue by xiaonalu** [mortazavilab/TALON#90]
Hi, how much memory is needed to run the TALON? I requested --cpus-per-task=8 --mem-per-cpu=5G, but received free():invalid next size (normal) error. or any other reason for this error? Thanks
Best
Xiaona

**Comment by fairliereese** [comment]
I would recommend using more memory than 5GB but this requirement also depends on how big the dataset you're analyzing is. How many reads do you have? 

I have recently been running TALON with 128GB of memory, for reference.

**Comment by niradsp** [comment]
Hello,
How can I control memory?  I have 42 samples, and the program seems to be using 400 GB memory, and counting.

Thanks in advance,
Nirad

**Comment by callumparr** [comment]
> Hello, How can I control memory? I have 42 samples, and the program seems to be using 400 GB memory, and counting.
> 
> Thanks in advance, Nirad

After initializing the database, you can run your samples in batches with TALON, albeit they are going into the same database using the same genome build. 

You could say run 10 samples at once, or run some other grouping that makes sense for your project (i.e. all replicates for each biological sample)

**Comment by niradsp** [comment]
> After initializing the database, you can run your samples in batches with TALON, albeit they are going into the same database using the same genome build.

Thank you.  That is exactly what I ended up doing.  My memory footprint is much lower now.
I have another question, but this time about reusing the database in question.
If I have both PacBio and Nanopore samples (each has 42 samples, and these are the same samples), how should I go about doing this?  I want obviously a unified list of novel transcript IDs.  For example, Talon0001 in Nanopore should be the same as Talon0001 in PacBio.
Here is what I am thinking.  Run Talon using PacBio and update the database.  Then run Nanopore and update the same database.  When generating abundance data, I should then specify the samples.  Any thoughts.
Not sure if running PacBio first and Nanopore next or vice versa will make a difference.  Since PacBio is more accurate, maybe it makes sense to run PacBIo first?

**Comment by fairliereese** [comment]
Thank you @callumparr, your advice is spot on! This is how we have been running our data through TALON as well. It's a bit of a slog, but it works. 

> Not sure if running PacBio first and Nanopore next or vice versa will make a difference. Since PacBio is more accurate, maybe it makes sense to run PacBIo first?

With regards to this question, hypothetically it doesn't make a difference. If you're running your data through the same database, you'll end up with novel transcript IDs that can be compared across any samples in the database. However TALON does choose the first read it sees to be the template for novel isoforms, so if you are worried about goodness of the novel models, you may want to run the PacBio data through as you're more confident about the molecules you'll see from that platform.
