### ISSUE TITLE
What reference to use?

### ISSUE THREAD

**Issue by callumparr** [mortazavilab/TALON#93]
I am currently starting with some full-length cDNA-PCR reads from Nanopore that have been mapped to hg38 using minimap2 in stranded manner.

The hg38.fa files I downloaded from UCSC contain "alt" assemblies and at first I thought perhaps this is not an issue. The original mappings mostly align to the major chr assemblies but after TALON I can see vast majority of read annotations coming from "alt" chromosome assemblies. 

I am unsure what reference genome file I should use for this type of analysis.

**Comment by fairliereese** [comment]
If you don't want a lot of these extra chromosomes, you might want to consider mapping to a version of the reference that excludes these scaffolds. 

Maybe try the reference that ENCODE uses, which should have far fewer (if any) alt chromosomes: https://www.encodeproject.org/files/GRCh38_no_alt_analysis_set_GCA_000001405.15/

**Comment by callumparr** [comment]
Thank you for your reply. I understand better now. Sorry for a noob question is there a corresponding annotation file to use with this or would gencode.v37 or v39 be OK to use?

**Comment by fairliereese** [comment]
Good question. All annotations assume a specific version of the reference genome. But since there are more releases of the annotations than reference genome, many annotations are compatible with the same genome. If you look at the [GENCODE annotation release history](https://www.gencodegenes.org/human/releases.html) under the "Genome assembly version", you'll see that both 39 and 37 are built on GRCh38, so you should be OK to use either of them.
