### ISSUE TITLE
PacBio isoseq to talon: best practices

### ISSUE THREAD

**Issue by rsalz** [mortazavilab/TALON#94]
Hi

**disclaimer, my question requires knowledge of isoseq: https://github.com/PacificBiosciences/IsoSeq/blob/master/isoseq-clustering.md

I did not see it specified in your documentation best practices of going from Isoseq to TALON (although I imagine many do this). The issue lies in the abundance. At the end of the isoseq pipeline, a full set of cleaned/clustered reads is returned with '.polished.hq.fasta.gz' suffix. It is simple enough to align this and put it into the TALON pipeline, but unfortunately the abundance information is missing/inaccurate since the clustering step of isoseq removes 'redundancy'.

Developers associated with PacBio have suggested [really annoying ways to get around this for people who still want to use TALON](https://github.com/Magdoll/cDNA_Cupcake/wiki/Handling-multiple-samples:-Creating-a-master-transcriptome). Would it not be just so much more simple if you accepted the 'cluster_report' for the talon_abundance step? Or would you suggest using the FLNC reads (after refinement but before clustering)?

Wondering if you guys already thought about it and what your thoughts are on this.

TIA!

**Comment by fairliereese** [comment]
Hi there,
For use with TALON, we run the IsoSeq pipeline through Refine but no further according to the steps outlined in [this document](https://www.encodeproject.org/documents/6d583a1d-d692-4511-b13b-c051822d861c/). I hope this helps!

**Comment by rsalz** [comment]
This is so helpful, thank you!! I have spent quite a bit of time examining the document and i have 2 follow up questions.

First, is there a reason you use `--ccs` instead of `--isoseq` in the lima step? I actually can't find a whole lot of information about how those are different and I'm wondering about why you chose what you did.
Second, I have been thusfar running TranscriptClean without the addition of short reads or variants, because I have neither done short read RNAseq on this dataset or called variants. I see in the protocol that you use the reference gtf as short read input. Would you recommend doing this in this case? Am I right to assume that I should leave out `--canonOnly` if i want to discover new isoforms?

**Comment by fairliereese** [comment]
Great, glad it was helpful!

After looking into it, it actually looks like this document is a bit outdated. We have since switched to using the `--isoseq` option. I also cannot find too much information about what the differences are, so can't offer much insight into that. 

With regards to TranscriptClean, I would indeed use the splice junctions from the reference GTF. The `--canonOnly` argument will actually keep reads that have canonical splice junctions used (ie the typical accepted splice donor and acceptor signals) OR have splice junctions that are non-canonical but annotated in the reference set of splice junctions (ie the one provided by the GTF). You would definitely find _more_ novel transcripts without this option, but we find a fair number of novel transcripts even with it, as many novel transcripts simply are new combinations of what we already see in the annotation.

**Comment by rsalz** [comment]
Okay thanks!
